### ISSUE TITLE
LogicException: Unable to register extension "nystudio107\typogrify\twigextensions\TypogrifyTwigExtension" as extensions have already been initialized

### ISSUE THREAD

**Issue by xinningsu** [nystudio107/craft3-typogrify#75]
The error  happens only when I create a new site in cms and visit the new site url first time. after refreshing new site page, the error is gone.

Craft CMS: 3.7.46
craft-typogrify: 1.1.19
twig/twig: v2.14.11

```
app_1    | 2022-08-31 17:06:03 [-][-][lc1ecqiqhs91labk06orh1jote][error][LogicException] LogicException: Unable to register extension "nystudio107\typogrify\twigextensions\TypogrifyTwigExtension" as extensions have already been initialized. in /app/vendor/twig/twig/src/ExtensionSet.php:145
app_1    | Stack trace:
app_1    | #0 /app/vendor/twig/twig/src/Environment.php(701): Twig\ExtensionSet->addExtension()
app_1    | #1 /app/vendor/craftcms/cms/src/web/View.php(362): Twig\Environment->addExtension()
app_1    | #2 /app/vendor/nystudio107/craft-typogrify/src/Typogrify.php(62): craft\web\View->registerTwigExtension()
app_1    | #3 /app/vendor/yiisoft/yii2/base/BaseObject.php(109): nystudio107\typogrify\Typogrify->init()
app_1    | #4 /app/vendor/yiisoft/yii2/base/Module.php(161): yii\base\BaseObject->__construct()
app_1    | #5 /app/vendor/craftcms/cms/src/base/Plugin.php(115): yii\base\Module->__construct()
app_1    | #6 [internal function]: craft\base\Plugin->__construct()
app_1    | #7 /app/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs()
app_1    | #8 /app/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
app_1    | #9 /app/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
app_1    | #10 /app/vendor/craftcms/cms/src/Craft.php(61): yii\BaseYii::createObject()
app_1    | #11 /app/vendor/craftcms/cms/src/services/Plugins.php(948): Craft::createObject()
app_1    | #12 /app/vendor/craftcms/cms/src/services/Plugins.php(232): craft\services\Plugins->createPlugin()
app_1    | #13 /app/vendor/craftcms/cms/src/base/ApplicationTrait.php(1487): craft\services\Plugins->loadPlugins()
app_1    | #14 /app/vendor/craftcms/cms/src/web/Application.php(99): craft\web\Application->_postInit()
app_1    | #15 /app/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
app_1    | #16 /app/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct()
app_1    | #17 [internal function]: yii\base\Application->__construct()
app_1    | #18 /app/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs()
app_1    | #19 /app/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
app_1    | #20 /app/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
app_1    | #21 /app/vendor/craftcms/cms/src/Craft.php(61): yii\BaseYii::createObject()
app_1    | #22 /app/vendor/craftcms/cms/bootstrap/bootstrap.php(247): Craft::createObject()
app_1    | #23 /app/vendor/craftcms/cms/bootstrap/web.php(51): require('...')
app_1    | #24 /app/web/index.php(81): require('...')
app_1    | #25 {main}
```

I tried to print `extensions` here: https://github.com/twigphp/Twig/blob/v2.14.11/src/ExtensionSet.php#L422
The first time `typogrify` is not in `extensions`, so I got 500, after refreshing the page, `typogrify` is in `extensions`, and the page works.

Any idea why?

cc @khalwat

**Comment by khalwat** [comment]
Something (most likely a plugin) has loaded before Typogrify, and has initialized Twig -- this is something plugins should not do until all plugins have loaded.

So while the error is thrown by Typogrify, the real error is something else (likely another plugin) doing something with Twig that causes it to initialize itself before Typogrify loads.
